language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: H0MUt4BsCvZIBF87iHRkUVn+seuy6vn/geiEVOXwI2+sBBrMwnUyX4ngWN86vGARgCLfTqa+3N1ZdbQlJf51qBND4qVLRPImNxAaw7TH7xRGtup788yCfhp1Xluto/v/fgfZIjkRZutTQqo7srD4Ru02vjOnYHvrEfKlWvqpQr9M/3Sg9aHz9ucBNIk42y0UKX6d22dRlHd28HV7pscd26+FPn+5yaywuHsQPz/16ZVSPZbZOKzQCAZxf05kMNutc7nJJxooQER3xXZsLt1sH1Bwbx6j7h8NlBGMXGjHMVdJpzjqs8epzumymf7XtZT/CTvY6iUijk+w8ZCrwB/YPU0MtDbFKYAR6GdSzK0IeVvA9zkEiNlz3UASIDiRfnsFBsfpZLkSjaK4y65d93j09iTyIm3fdKUKslEfeWyuYvv5gu1ZdtO/sQMPo1QvxeNGm8G6VtStxbOUcqvV3vwqWFKS1lz/mxwcGhN1sFgK2KWWrXySr6VWf4z3KJMHTdW5eeLnPtHgXucm7wiWgWU0ERkkJgn5AAM2DfFi9jFdqo8rgh79N+/QRfX79ag9idrlPXNBbMaQbiXEiwAx/SH+s+3JIP4hlSZXwHKptn5Px3BUQ7aKHs4dm2iSj1oeH+a1DCICQo9pDE4WwnMlo8Styht2F183ukURoCN74rbIfxE=
  app: tranquil-atoll-64381
  on:
    repo: eapostol/sample-travis-heroku-repo
